######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 26 16:00:30 2011
######################################################################

CONFIG += qt crypto debug qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../libdissent/config.hpp \
           ../libdissent/crypto.hpp \
           ../libdissent/QByteArrayUtil.hpp \
           ../libdissent/random_util.hpp
SOURCES += testconfig.cc \
           testcrypto.cc \
           testqbytearrayutil.cc \
           testrandom_util.cc \
           ../libdissent/config.cc \
           ../libdissent/crypto.cc \
           ../libdissent/QByteArrayUtil.cc \
           ../libdissent/random_util.cc
