######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 19:31:21 2011
######################################################################

CONFIG += qt crypto qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../libdissent/crypto.hpp
SOURCES += testcrypto.cc ../libdissent/crypto.cc
