######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 23 19:31:21 2011
######################################################################

include(crypto.pri)

CONFIG += qt crypto dll debug qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../libdissent/crypto.hpp
SOURCES += testcrypto.cc testmain.cc ../libdissent/crypto.cc
