version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - interfacebloat
    - lll
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tparallel
    - unparam
    - unused
    - usestdlibvars
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 20
    gocritic:
      disabled-checks:
        - captLocal
    gosec:
      excludes:
        - G107
        - G404
        - G115
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    nakedret:
      max-func-lines: 10
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: ^//\s*go:generate\s
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - errorlint
        source: ^\s+if _, ok := err\.\([^.]+\.InternalError\); ok {
      - linters:
          - unparam
          - unused
        path: .skeleton
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - gosec
          - lll
          - noctx
          - unparam
          - wrapcheck
        path: .*_test.go
      - linters:
          - gocritic
        text: 'appendAssign:'
      - linters:
          - revive
        text: 'unexported-return:'
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows declaration'
      - linters:
          - interfacebloat
        path: group.go
      - linters:
          - funlen
          - ineffassign
        path: group/edwards25519/scalar.go
      - linters:
          - lll
        path: group/edwards25519/const.go
      - linters:
          - funlen
        path: group/edwards25519/fe.go
      - linters:
          - cyclop
          - funlen
          - gocognit
          - gocyclo
        path: share/dkg/pedersen
      - linters:
          - ineffassign
        path: group/edwards25519/scalar.go
      - linters:
          - errcheck
        path: pairing/(bls12381|bn254)/.
        text: Error return value is not checked
      - linters:
          - staticcheck
        path: encrypt/ibe/ibe.go
        text: var Gid should be GID|var hrGid should be hrGID|rGid should be rGID|var hGidT should be hGIDT|var GidT should be GIDT
      - linters:
          - errcheck
        path: pairing/bls12381/circl/*|pairing/bls12381/kilic/*
        text: Error return value is not checked
      - linters:
          - forbidigo
        path: benchmark/*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
