######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 18 00:37:55 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cc mainwindow.cc
