######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 18 11:23:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h messagetablemodel.h
FORMS += mainwindow.ui
SOURCES += main.cc mainwindow.cc messagetablemodel.cc
