######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 18 14:11:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += handler.hpp
SOURCES += handler.cc main.cc
