// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pedersen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I             *uint32                `protobuf:"varint,1,req,name=i" json:"i,omitempty"`
	V             []byte                 `protobuf:"bytes,2,req,name=v" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriShare) Reset() {
	*x = PriShare{}
	mi := &file_pedersen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriShare) ProtoMessage() {}

func (x *PriShare) ProtoReflect() protoreflect.Message {
	mi := &file_pedersen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriShare.ProtoReflect.Descriptor instead.
func (*PriShare) Descriptor() ([]byte, []int) {
	return file_pedersen_proto_rawDescGZIP(), []int{0}
}

func (x *PriShare) GetI() uint32 {
	if x != nil && x.I != nil {
		return *x.I
	}
	return 0
}

func (x *PriShare) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type Deal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     []byte                 `protobuf:"bytes,1,req,name=sessionID" json:"sessionID,omitempty"`
	SecShare      *PriShare              `protobuf:"bytes,2,req,name=secShare" json:"secShare,omitempty"`
	T             *int64                 `protobuf:"zigzag64,3,req,name=t" json:"t,omitempty"`
	Commitments   [][]byte               `protobuf:"bytes,4,rep,name=commitments" json:"commitments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deal) Reset() {
	*x = Deal{}
	mi := &file_pedersen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deal) ProtoMessage() {}

func (x *Deal) ProtoReflect() protoreflect.Message {
	mi := &file_pedersen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deal.ProtoReflect.Descriptor instead.
func (*Deal) Descriptor() ([]byte, []int) {
	return file_pedersen_proto_rawDescGZIP(), []int{1}
}

func (x *Deal) GetSessionID() []byte {
	if x != nil {
		return x.SessionID
	}
	return nil
}

func (x *Deal) GetSecShare() *PriShare {
	if x != nil {
		return x.SecShare
	}
	return nil
}

func (x *Deal) GetT() int64 {
	if x != nil && x.T != nil {
		return *x.T
	}
	return 0
}

func (x *Deal) GetCommitments() [][]byte {
	if x != nil {
		return x.Commitments
	}
	return nil
}

type EncryptedDeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dhkey         []byte                 `protobuf:"bytes,1,req,name=dhkey" json:"dhkey,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,req,name=signature" json:"signature,omitempty"`
	Cipher        []byte                 `protobuf:"bytes,4,req,name=cipher" json:"cipher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedDeal) Reset() {
	*x = EncryptedDeal{}
	mi := &file_pedersen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDeal) ProtoMessage() {}

func (x *EncryptedDeal) ProtoReflect() protoreflect.Message {
	mi := &file_pedersen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDeal.ProtoReflect.Descriptor instead.
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return file_pedersen_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptedDeal) GetDhkey() []byte {
	if x != nil {
		return x.Dhkey
	}
	return nil
}

func (x *EncryptedDeal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EncryptedDeal) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

type EncryptedDealV3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dhkey         []byte                 `protobuf:"bytes,1,req,name=dhkey" json:"dhkey,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,req,name=signature" json:"signature,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce" json:"nonce,omitempty"`
	Cipher        []byte                 `protobuf:"bytes,4,req,name=cipher" json:"cipher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedDealV3) Reset() {
	*x = EncryptedDealV3{}
	mi := &file_pedersen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDealV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDealV3) ProtoMessage() {}

func (x *EncryptedDealV3) ProtoReflect() protoreflect.Message {
	mi := &file_pedersen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDealV3.ProtoReflect.Descriptor instead.
func (*EncryptedDealV3) Descriptor() ([]byte, []int) {
	return file_pedersen_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptedDealV3) GetDhkey() []byte {
	if x != nil {
		return x.Dhkey
	}
	return nil
}

func (x *EncryptedDealV3) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EncryptedDealV3) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedDealV3) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

var File_pedersen_proto protoreflect.FileDescriptor

const file_pedersen_proto_rawDesc = "" +
	"\n" +
	"\x0epedersen.proto\"&\n" +
	"\bPriShare\x12\f\n" +
	"\x01i\x18\x01 \x02(\rR\x01i\x12\f\n" +
	"\x01v\x18\x02 \x02(\fR\x01v\"{\n" +
	"\x04Deal\x12\x1c\n" +
	"\tsessionID\x18\x01 \x02(\fR\tsessionID\x12%\n" +
	"\bsecShare\x18\x02 \x02(\v2\t.PriShareR\bsecShare\x12\f\n" +
	"\x01t\x18\x03 \x02(\x12R\x01t\x12 \n" +
	"\vcommitments\x18\x04 \x03(\fR\vcommitments\"[\n" +
	"\rEncryptedDeal\x12\x14\n" +
	"\x05dhkey\x18\x01 \x02(\fR\x05dhkey\x12\x1c\n" +
	"\tsignature\x18\x02 \x02(\fR\tsignature\x12\x16\n" +
	"\x06cipher\x18\x04 \x02(\fR\x06cipher\"s\n" +
	"\x0fEncryptedDealV3\x12\x14\n" +
	"\x05dhkey\x18\x01 \x02(\fR\x05dhkey\x12\x1c\n" +
	"\tsignature\x18\x02 \x02(\fR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x16\n" +
	"\x06cipher\x18\x04 \x02(\fR\x06cipherB\bZ\x06proto/"

var (
	file_pedersen_proto_rawDescOnce sync.Once
	file_pedersen_proto_rawDescData []byte
)

func file_pedersen_proto_rawDescGZIP() []byte {
	file_pedersen_proto_rawDescOnce.Do(func() {
		file_pedersen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pedersen_proto_rawDesc), len(file_pedersen_proto_rawDesc)))
	})
	return file_pedersen_proto_rawDescData
}

var file_pedersen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pedersen_proto_goTypes = []any{
	(*PriShare)(nil),        // 0: PriShare
	(*Deal)(nil),            // 1: Deal
	(*EncryptedDeal)(nil),   // 2: EncryptedDeal
	(*EncryptedDealV3)(nil), // 3: EncryptedDealV3
}
var file_pedersen_proto_depIdxs = []int32{
	0, // 0: Deal.secShare:type_name -> PriShare
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pedersen_proto_init() }
func file_pedersen_proto_init() {
	if File_pedersen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pedersen_proto_rawDesc), len(file_pedersen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pedersen_proto_goTypes,
		DependencyIndexes: file_pedersen_proto_depIdxs,
		MessageInfos:      file_pedersen_proto_msgTypes,
	}.Build()
	File_pedersen_proto = out.File
	file_pedersen_proto_goTypes = nil
	file_pedersen_proto_depIdxs = nil
}
