#ifndef DISSENT_CRYPTO_CPP_DIFFIE_HELLMAN_KEY_H_GUARD
#define DISSENT_CRYPTO_CPP_DIFFIE_HELLMAN_KEY_H_GUARD

#include "DiffieHellman.hpp"
#include "cryptopp/dh.h"

namespace Dissent {
namespace Crypto {
  /**
   * Cpp DiffieHellman Wrapper
   */
  class CppDiffieHellman : public DiffieHellman {
    public:
      /**
       * Constructor
       * @param data empty, private key, or seed if seed is true
       * @param seed specifies is data is a private key or a seed
       */
      explicit CppDiffieHellman(const QByteArray &data = QByteArray(),
          bool seed = false);

      /**
       * Destructor
       */
      virtual ~CppDiffieHellman() {}

      /**
       * Retrieves the public component of the Diffie-Hellman agreement
       */
      virtual QByteArray GetPublicComponent() const { return _public_key; }

      /**
       * Retrieves the private component of the Diffie-Hellman agreement
       */
      virtual QByteArray GetPrivateComponent() const { return _private_key; }

      /**
       * Return the shared secret given the other sides public component
       * @param remote_pub the other sides public component
       */
      virtual QByteArray GetSharedSecret(const QByteArray &remote_pub) const;

      /**
       * Return a non-interactive zero-knowledge proof of a shared Diffie-Hellman
       * secret.
       * A wants to prove to C that the shared secret between A and B was correctly
       * generated by A. A then calls this method as:
       * 
       *    private_key_A->ProveSharedSecret(public_key_B)
       *
       * and sends the output to C
       */
      virtual QByteArray ProveSharedSecret(const QByteArray &remote_pub) const;

      /**
       * Verify a non-interactive zero-knowledge proof of a shared Diffie-Hellman secret.
       * A wants to prove to C that the shared secret between A and B was correctly
       * generated by A. The verifier C then calls this method as:
       * 
       *    public_key_A->VerifySharedSecret(public_key_B)
       *
       * @returns QByteArray() if verification fails, otherwise returns the shared secret
       */
      virtual QByteArray VerifySharedSecret(const QByteArray &prover_pub,
          const QByteArray &remote_pub, const QByteArray &proof) const;

      /**
       * Get the digest of a list of integers (represented as ByteArrays)
       * @param list of integers
       */
      QByteArray HashIntegers(const QList<QByteArray> &list) const;

      inline static const CryptoPP::Integer &GetPInt()
      {
        if(_p_int == CryptoPP::Integer::Zero()) {
          Init();
        }
        return _p_int;
      }

      inline static const CryptoPP::Integer &GetQInt()
      {
        if(_q_int == CryptoPP::Integer::Zero()) {
          Init();
        }
        return _q_int;
      }

      inline static const CryptoPP::Integer &GetGInt()
      {
        if(_g_int == CryptoPP::Integer::Zero()) {
          Init();
        }
        return _g_int;
      }

    private:
      static void Init();
      static const int ZeroKnowledgeProofHeaderSize = 12;
      static CryptoPP::Integer  _p_int, _q_int, _g_int;
      CryptoPP::DH _dh_params;
      QByteArray _public_key;
      QByteArray _private_key;
  };
}
}

#endif
