package toy

import (
	"github.com/dedis/kyber"
)

type group struct{}

// Group is a shared instance of a toy group, where the points are
// generated by modular exponentiation of the element 2,
// and where the generated group has prime order.
var Group group

// GroupModulus is the modulus in which the exponentiation takes place.
const GroupModulus point = 127

// GroupOrder is the order of the generated group.
const GroupOrder scalar = 7

func (g group) String() string {
	return "toy"
}

func (g group) ScalarLen() int {
	return 1
}

func (g group) Scalar() kyber.Scalar {
	return new(scalar)
}

func (g group) PointLen() int {
	return 1
}

func (g group) Point() kyber.Point {
	return new(point)
}
